---
title: "Reproducible Research: Peer Assessment 1"
author: "Nikhil D."
date: "July 7, 2021"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data (library()/setwd() omitted for clarity)

```{r,echo=TRUE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(ggpubr)

# Set setwd() to working directory containing data
setwd("C:/Users/nkd29/Desktop/Nikhils_Stuff/01_Career/03_Courses/Coursera_R_Data_Science_Johns_Hopkins/05_Repoducible_Research/Project_1/RepData_PeerAssessment1")

```

```{r, echo=TRUE}
list.files()

data <- tbl_df(read.csv('activity.csv'))
```

## What is mean total number of steps taken per day?

```{r}
# total steps per day
data_by_day <- data %>%  group_by(date)
tot_daily_steps <- summarise(data_by_day,sum(steps))


# histogram
ggplot(na.omit(tot_daily_steps), aes(x=`sum(steps)`)) + 
  geom_histogram(boundary = 0,
                 binwidth = 2500,
                 col='black',
                 fill='blue',
                 alpha=.25) +
  ggtitle('Histogram of steps per day') +
  xlab('Total Steps') +
  ylab('Frequency') +
  theme(plot.title = element_text(hjust=0.5)) +
  scale_x_continuous(breaks = seq(0,25000,2500)) +
  scale_y_continuous(breaks = seq(0,25,5))


# mean and median
mean(tot_daily_steps$`sum(steps)`, na.rm = TRUE)
median(tot_daily_steps$`sum(steps)`, na.rm = TRUE)
```

## What is the average daily activity pattern?
```{r daily-activity}
# time series plot
data_by_interval <- group_by(na.omit(data),interval)
avg_steps <- summarize(data_by_interval,mean(steps))

ggplot(avg_steps,aes(x=interval,y=`mean(steps)`)) + geom_line()

# Which 5-minute interval, on average across all the days in the dataset, contains the maximum 
# number of steps?
max_avg_steps <- max(avg_steps$`mean(steps)`)
max_avg_steps

max_avg_int <- avg_steps$interval[match(max_avg_steps, avg_steps$`mean(steps)`)]
max_avg_int
```

## Imputing missing values
```{r}
# get total number of NA values
tot_na <- sum(is.na(data$steps))
tot_na

# add index column
data2 <- data %>% mutate(int_avg_index=match(data$interval, avg_steps$interval)) 

# use index to lookup calculated averages for each interval. Put into new column
data2$int_mean <- avg_steps$`mean(steps)`[data2$int_avg_index]

# replace only NA values with the looked up averages
data2$steps[which(is.na(data2$steps))] <- data2$int_mean


# total steps per day
data_by_day2 <- data2 %>%  group_by(date)
tot_daily_steps2 <- summarise(data_by_day2,sum(steps))


# plot again: histogram
# ggplot(data2, aes(x=steps)) + geom_histogram()

ggplot(na.omit(tot_daily_steps2), aes(x=`sum(steps)`)) + 
  geom_histogram(boundary = 0,
                 binwidth = 2500,
                 col='black',
                 fill='red',
                 alpha=.25) +
  ggtitle('Histogram of steps per day (Imputed NAs)') +
  xlab('Total Steps') +
  ylab('Frequency') +
  theme(plot.title = element_text(hjust=0.5)) +
  scale_x_continuous(breaks = seq(0,25000,2500)) +
  scale_y_continuous(breaks = seq(0,25,5))


# mean and median: 
mean(tot_daily_steps2$`sum(steps)`)
median(tot_daily_steps2$`sum(steps)`)

```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
data2$day <- wday(ymd(data2$date),label=TRUE)

# data2$is_wknd <- ifelse(data2$day=)
data2$wknd <- ifelse(data2$day == "Sat"|data2$day=="Sun","weekend","weekday")

data2_by_int_wday <- data2 %>% filter(wknd=="weekday") %>% group_by(interval) %>% summarise(mean(steps))
data2_by_int_wknd <- data2 %>% filter(wknd=="weekend") %>% group_by(interval) %>% summarise(mean(steps))

data2_by_int_wday
data2_by_int_wknd

p_wday <- ggplot(data2_by_int_wday,aes(x=interval,y=`mean(steps)`)) + geom_line()

p_wknd <- ggplot(data2_by_int_wknd,aes(x=interval,y=`mean(steps)`)) + geom_line()

ggarrange(p_wday,p_wknd,ncol=1,nrow=2)

```

